### ISSUE TITLE
Support import method from app shell

### ISSUE THREAD

**Issue by carvinlo** [FlorianRappl/piral-webpack-tools#11]
piral is getting better and stronger！！

The situation is like this
![image](https://user-images.githubusercontent.com/5674761/80947651-3147a580-8e23-11ea-95ce-89ea4856754a.png)
There are two completely independent teams developing the same micro front-end project. Team A is responsible for developing App shell and pilet 1, and team B is responsible for developing pilet 2. Team A developed the App shell and pilet 1 in a monorepo. Team B's sub-application pilet 2 obtained the development code released by team A through the Npm package. The App shell is similar to siteless and provides an initializePiral method. The initialPiral rendering application is used in the pilet2 development mode, and a setup function is provided for production release.
Then it seems that the import method from the app shell is not supported now.
![image](https://user-images.githubusercontent.com/5674761/80949529-c26c4b80-8e26-11ea-86b5-d5e3e2eaa18e.png)
![image](https://user-images.githubusercontent.com/5674761/80949470-af597b80-8e26-11ea-810a-9f138a9249b5.png)

Thank you for your precious time！

**Comment by carvinlo** [comment]
Such as：
app shell entry file
![image](https://user-images.githubusercontent.com/5674761/80954393-da949880-8e2f-11ea-9bc2-6e75e1a30450.png)
pilet entry file
![image](https://user-images.githubusercontent.com/5674761/80954715-80e09e00-8e30-11ea-9d39-ec6748d6a6c7.png)
Perhaps it can be provided to the pilet in debug mode through the `window.initializePiral` method.
And need a way to disable the app shell from automatically requesting pilet code in debug mode.
Waiting for your suggestion

**Comment by FlorianRappl** [comment]
Well, the `initializePiral` (or anything functional) should (ideally) not be exported from the app shell. Any reason for importing this (it should initialize on its own)? Why not just always initialize it?

Piral will (in the emulator mode) not use your feed URL, but will instead load from `/$pilet-api`, which exists in the `pilet debug` (or in case of webpack `pilet debug-wp`). Otherwise, for custom needs maybe the debugging tools could be helpful (https://github.com/smapiot/piral-inspector).

The app shell should only transport types. If you really want to transport functional pieces (e.g., functions or other values) then you can do that via explicitly setting the shared dependencies (see https://docs.piral.io/tutorials/15-share-dependencies#explicit-sharing-from-the-app-shell).

Does that help? Do I understand the issue correctly or am I missing something?

**Comment by carvinlo** [comment]
Just updated the latest version of 'piral-cli-webpack', the loading mode of `/ $ pilet-api` has been greatly improved in debugging, and there is no need for transport functional pieces anymore, thank you for your patience.
![image](https://user-images.githubusercontent.com/5674761/80966796-c9578600-8e47-11ea-909f-1aa1ba1d653f.png)
Stay tuned, thank you!

**Comment by FlorianRappl** [comment]
Awesome - thanks for the update :beers:!
