### ISSUE TITLE
Support to declare externals in plugins' package.json

### ISSUE THREAD

**Issue by carvinlo** [FlorianRappl/piral-webpack-tools#15]
As a part of the shell application, does the plugin automatically add `pilets.externals` to the` externals` of the app shell from the `package.json` of the referenced plugins, instead of manually adding` externals` when the app shell imports plugins `?

**Comment by FlorianRappl** [comment]
Yeah the externals of a pilet are the combination of the shared dependencies from the app shell and its own externals.

See:
https://github.com/FlorianRappl/piral-cli-webpack/blob/master/packages/pilet-webpack-plugin/src/index.ts#L23

Regarding import of plugins: With the exception of the core shared dependencies all other dependencies must be shared explicitly. So if you have a plugin that comes with a dependency (either directly or as peer) you will need to add it to the shared dependency explicitly. Otherwise, pilets cannot use it.

Hope that helps!

**Comment by carvinlo** [comment]
Got it, thanks!
