### ISSUE TITLE
Errors raised by WebSocket

### ISSUE THREAD

**Issue by carvinlo** [FlorianRappl/piral-webpack-tools#21]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [ ] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [ ] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

piral-cli@0.11.5
IE11
piral-cli-webpack@0.5.3

## Description

The page refresh is always triggered by webpack-dev-server. Under IE11, [const ws = new WebSocket(updateTarget);](https://github.com/smapiot/piral/blob/f6cb7c22c8a663f0c6ebc8c6ab05f852a6748b9b/src/framework/piral-core/src/helpers.tsx#L136) will trigger a `read ECONNRESET` error after the page is automatically refreshed.

## Steps to Reproduce

1. Debug pilet in ie11
2. Manually refresh the ie browser or modify the code to trigger the page to automatically refresh
3. webpack-dev-server crashed and output an error in the console:
```
Unhandled 'error' event
Error: read ECONNRESET
```
4. Works well on chrome browser

## Expected behavior

[What you expected to happen]

## Actual behavior

[What actually happened]

## Possible Origin / Solution

If comment out this [socket](https://github.com/smapiot/piral/blob/f6cb7c22c8a663f0c6ebc8c6ab05f852a6748b9b/src/framework/piral-core/src/helpers.tsx#L136) code, it works well on ie11.
When I replace WebSocket with sockjs-client to be compatible with IE11([the code](https://github.com/smapiot/piral/compare/develop...carvinlo:patch-1)), it works fine on chrome and ie11. Is this feasible?

**Comment by FlorianRappl** [comment]
Well, we will not replace the simple (built-in) `WebSocket` with another dependency - especially if its only for IE11.

Our debugging target is Chrome / Firefox / the new Edge / the latest browsers. Our aim is to support browsers up to IE11 for published use.

I think the issue is rather that `piral-cli-webpack` does not use the kras middleware as the standard bundler does. In this case its a won't fix for the current `piral-cli-webpack` and it will automatically work with the new version that is compatible with `piral-cli` 0.11.5 onwards.

I'll leave the issue open until we know.

**Comment by carvinlo** [comment]
Perhaps, temporarily block out the socket in the Internet Explorer browser to ensure that it does not crash under Internet Explorer?

**Comment by FlorianRappl** [comment]
> Perhaps, temporarily block out the socket in the Internet Explorer browser to ensure that it does not crash under Internet Explorer?

Well, the proposed "fix" has nothing to do with `WebSocket` -> you change rather the target URL. As already written this has more to do with `piral-cli-webpack` using directly Webpack, instead of using the kras middleware.

If we would drop out that code in IE, it would only make the code more complicated and the result would be the same; you'd need to reload manually if your pilet changed. In this case I would argue that making just the code more complicated would not serve the purpose and we should leave it as-is.

That the error is shown in the console should not have any negative impact otherwise. This is not per se a crash, its rather just an unhandled error from the `WebSocket`. The rest should just run fine (its like an error in the handler of a click event; this also does not impact the surrounding code and only has an effect on this particular handler).

**Comment by carvinlo** [comment]
Thanks for your description. Do you mean this problem does not exist after switching to kras middleware?

**Comment by FlorianRappl** [comment]
Yes. As far as I can see it the problem only exists because the endpoint is not there. You just change the endpoint. The endpoint would be there with kras.

**Comment by carvinlo** [comment]
Work fine with kras under ie11! perfect!
